# ceth-backend/Dockerfile.prod
FROM node:18 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:18
WORKDIR /app
COPY --from=builder /app /app
# dotenv จะอ่าน .env ได้เพราะเราจะ mount เข้ามาภายหลัง
CMD ["node", "dist/server.js"]
