version: "3.9"
services:
  postgres:
    image: postgres:13
    container_name: pgContainer
    environment:
      POSTGRES_USER: unizal-dev
      POSTGRES_PASSWORD: unizal_888
      POSTGRES_DB: ceth-database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

volumes:
  postgres_data:
    driver: local

networks:
  backend_network:
    driver: bridge
